name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            sudo apt update
            sudo apt install -y docker.io git curl

            sudo systemctl start docker
            sudo systemctl enable docker

            if [ ! -f /usr/local/bin/docker-compose ]; then
              sudo curl -L https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            if [ ! -d "hospital_management_system" ]; then
              git clone ${{ secrets.REPO_URL }} hospital_management_system
            fi

            cd hospital_management_system
            git pull

            cat > .env <<'EOF'
            POSTGRES_DB=${{ secrets.DB_NAME }}
            POSTGRES_USER=${{ secrets.DB_USER }}
            POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DEBUG=False
            EOF

            sudo docker-compose down
            sudo docker-compose up -d --build

            sudo docker-compose exec -T backend python manage.py migrate
            sudo docker-compose exec -T backend python manage.py collectstatic --noinput